# Generated by Django 3.2.12 on 2022-02-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_image/default.jpg', null=True, upload_to='profile_image/'),
        ),
    ]
